version: '2'
services:
    ianvs-app:
        image: ianvs
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ianvs-postgresql:5432/ianvs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ianvs-postgresql:
        extends:
            file: postgresql.yml
            service: ianvs-postgresql
